### PR TITLE
terraform get and gofmt

### PR DESCRIPTION
**Pull request by jeffastorey**
#15 running terraform get before applying terraform commands. Also ran gofmt for some cleanup.

### CODE REVIEW

**Comment by sl1pm4t** [comment]
@tboerger  - Could we also merge this one, our terraform configs usually point to modules in git, so we need `terraform get` behaviour this PR provides.

**Comment by tboerger** [comment]
LGTM

**Comment by jackspirou** [comment]
LGTM

**Comment by jackspirou** [comment]
@jeffastorey this will need a rebase or pull as well

**Comment by desktophero** [comment]
`terraform get` ... sweet!

**Comment by jeffastorey** [comment]
@jackspirou rebased and updated

**Pull request merged**
