### PR TITLE
Added initial .drone.sec

### PR DESCRIPTION
**Pull request by tboerger**

### CODE REVIEW

**Comment by tboerger** [comment]
LGTM

**Comment by as0bu** [comment]
:+1: thanks again @tboerger. @jackspirou could I get this merge? :smiley:

**Comment by Bugagazavr** [comment]
LGTM

**Comment by tboerger** [comment]
Publish is done http://beta.drone.io/drone-plugins/drone-terraform/33

**Comment by as0bu** [comment]
Thanks again!

**Pull request merged**
