### PR TITLE
adding ability to change root dir for commands

### PR DESCRIPTION
**Pull request by jeffastorey**
Conflicts:
	main.go

Adds the ability to change the root dir for terraform commands in case you have multiple folders in a project. Also ran gofmt for some cleanup.

### CODE REVIEW

**Comment by tboerger** [comment]
LGTM

**Comment by jackspirou** [comment]
LGTM

**Comment by jackspirou** [comment]
@jeffastorey you might need to rebase

**Comment by jeffastorey** [comment]
@jackspirou did an update branch from here - should be ok now

**Pull request merged**
