### PR TITLE
Update to use terraform 0.6.11

### PR DESCRIPTION
**Pull request by jmccann**
I ran into bug https://github.com/hashicorp/terraform/issues/1783 which is addressed by updating to terraform 0.6.11.

### CODE REVIEW

**Comment by tboerger** [comment]
LGTM

**Comment by jackspirou** [comment]
LGTM

**Comment by jackspirou** [comment]
@jmccann Looks like this branch is out of date. You will need to git pull or git rebase.

**Comment by jmccann** [comment]
@jackspirou rebase done

**Comment by jackspirou** [comment]
LGTM

**Pull request merged**
