### PR TITLE
Sensitive Flag to suppress command trace output

### PR DESCRIPTION
**Pull request by jmccann**
I've been passing sensitive info as vars to be used by the terraform commands.  Therefore I'd like the ability to suppress the command trace output in the logs.

### CODE REVIEW

**Comment by tboerger** [comment]
I think I would just drop the trace command :D

**Comment by jmccann** [comment]
@tboerger I was thinking of perhaps checking if DEBUG was set to true and printing in that scenario ... it was useful for me in getting started with this plugin.  Should I go that route instead?

**Comment by tboerger** [comment]
I don't have a strong opinion on that. You get my LGTM and the rest should be decided by somebody else like @bradrydzewski :)
I'm not using this plugin anyway.

**Comment by bradrydzewski** [comment]
@jmccann the approach we've taken with some of the other plugins is to trace a command that is omits sensitive data. Is something like this possible? Is it possible to identify which args are sensitive?

**Comment by jackspirou** [comment]
@bradrydzewski I know I have seen other examples of other plugins with that approach.  Offhand do you know one?

**Comment by jmccann** [comment]
@bradrydzewski I'm doing something like the following in my `.drone.yml`:

```yaml
deploy:
  terraform:
    image: jmccann/drone-terraform
    dry_run: false
    remote:
      backend: swift
      config:
        path: drone/terraform
    vars:
      chef_validator_name: username
      chef_validator_key: "$$CHEF_VALIDATOR_KEY"
```

So as you can see, I have a var that is sensitive (`chef_validator_key `) and a var that is not sensitive (`chef_validator_name `).  So some solutions I see to the problem:

1. Add the sensitive flag like the PR has to globally hide command trace
2. Check for the sensitive flag as part of each var key to hide the var contents rather then the commands themselves.  So in the following example it would hide contents of `chef_validator_key ` but still show `chef_validator_name `.

```yaml
deploy:
  terraform:
    image: jmccann/drone-terraform
    dry_run: false
    remote:
      backend: swift
      config:
        path: drone/terraform
    vars:
      chef_validator_name: username
      chef_validator_key: "$$CHEF_VALIDATOR_KEY"
        sensitive: true
```

3. Similar to 1, hide the commands globally but using debug rather then create a sensitive flag globally.
4. Show commands but hide contents of ALL `vars` values.  This could be controlled on/off with a `sensitive` flag and/or checking DEBUG.

Or maybe someone else has another idea?  :)

**Comment by tboerger** [comment]
LGTM

**Comment by tboerger** [comment]
Needs to be rebased

**Comment by jackspirou** [comment]
other than rebase LGTM

**Comment by jmccann** [comment]
@tboerger @jackspirou There were some conflicts I had to address during the rebase.  So feel free to rereview.

**Comment by jackspirou** [comment]
still LGTM

**Pull request merged**
